#!/usr/bin/env python3
"""
Agent Definition Generator

Reads a JSON file containing agent specification data collected from the
agent-scaffolder interview process and produces a formatted markdown document.

Usage:
    python generate_agent_definition.py input.json -o output.md

Input JSON structure (all fields optional — omitted fields are skipped in output):
    See the schema in references/agent-definition-schema.md for field details.
"""

import json
import sys
import argparse
from datetime import date
from pathlib import Path


def load_schema() -> dict:
    """Return a template mapping section IDs to their markdown templates."""
    return {
        "header": (
            "# {name} \u2014 Agent Definition\n\n"
            "> **Version:** 1.0\n"
            "> **Date:** {date}\n"
            "> **Platform:** Platform-agnostic\n\n"
        ),
        "1_identity": (
            "## 1. Identity & Purpose\n\n"
            "### Agent Name\n\n{name}\n\n"
            "### Primary Role\n\n{role}\n\n"
            "### Mission Statement\n\n{mission}\n\n"
            "### Target Audience\n\n{audience}\n\n"
        ),
        "2_capabilities": (
            "## 2. Capabilities & Personality\n\n"
            "### Core Capabilities\n\n{capabilities}\n\n"
            "### Interaction Style & Personality\n\n"
            "- **Tone:** {tone}\n"
            "- **Personality traits:** {traits}\n"
            "- **Communication cadence:** {cadence}\n\n"
            "### Languages\n\n{languages}\n\n"
        ),
        "3_tools": (
            "## 3. Tools, Knowledge & Integrations\n\n"
            "### External Tools & APIs\n\n{tools}\n\n"
            "### Knowledge Base\n\n{knowledge_base}\n\n"
        ),
        "4_memory": (
            "## 4. Memory & Context\n\n"
            "### Memory Model\n\n{memory_model}\n\n"
            "### Context Scope\n\n{context_scope}\n\n"
        ),
        "5_constraints": (
            "## 5. Constraints, Safety & Quality\n\n"
            "### Boundaries & Limitations\n\n{boundaries}\n\n"
            "### Error Handling & Fallbacks\n\n{error_handling}\n\n"
            "### Quality Standards\n\n{quality}\n\n"
        ),
        "6_output": (
            "## 6. Output & Interaction Format\n\n"
            "### Output Types\n\n{output_types}\n\n"
            "### Communication Medium\n\n{medium}\n\n"
            "### Formatting & Style Guide\n\n{style_guide}\n\n"
        ),
        "7_example": (
            "## 7. Example Interaction\n\n"
            "```\n"
            "User: {example_input}\n"
            "Agent: {example_output}\n"
            "```\n\n"
        ),
        "footer": (
            "---\n\n"
            "*Generated by agent-scaffolder*\n"
        ),
    }


def format_list(items, bullet="-"):
    """Convert a list of strings or a string into markdown list items."""
    if not items:
        return "*No information provided.*"
    if isinstance(items, str):
        return items
    lines = []
    for item in items:
        if isinstance(item, dict):
            for k, v in item.items():
                lines.append(f"{bullet} **{k}:** {v}")
        else:
            lines.append(f"{bullet} {item}")
    return "\n".join(lines)


def format_table(rows, headers=None):
    """Convert a list of dicts into a markdown table."""
    if not rows:
        return "*No information provided.*"
    if headers is None:
        headers = list(rows[0].keys())
    col_count = len(headers)
    separator = "| " + " | ".join("---" for _ in headers) + " |"
    lines = ["| " + " | ".join(headers) + " |", separator]
    for row in rows:
        vals = [str(row.get(h, "")) for h in headers]
        lines.append("| " + " | ".join(vals) + " |")
    return "\n".join(lines)


def generate(data: dict) -> str:
    """Generate a markdown agent definition document from structured data."""
    schema = load_schema()
    today = date.today().isoformat()
    name = data.get("name", "Unnamed Agent")
    sections = []

    # Header
    sections.append(schema["header"].format(name=name, date=today))

    # Section 1: Identity & Purpose
    sections.append(schema["1_identity"].format(
        name=name,
        role=data.get("role", "*Not specified.*"),
        mission=data.get("mission", "*Not specified.*"),
        audience=data.get("audience", "*Not specified.*"),
    ))

    # Section 2: Capabilities & Personality
    caps = data.get("capabilities", [])
    sections.append(schema["2_capabilities"].format(
        capabilities=format_list(caps),
        tone=data.get("tone", "*Not specified.*"),
        traits=data.get("personality_traits", "*Not specified.*"),
        cadence=data.get("cadence", "*Not specified.*"),
        languages=data.get("languages", "*Not specified.*"),
    ))

    # Section 3: Tools, Knowledge & Integrations
    tools = data.get("tools", [])
    tools_str = format_table(tools) if tools and isinstance(tools[0], dict) else format_list(tools)
    kb = data.get("knowledge_base", [])
    kb_str = format_list(kb)
    sections.append(schema["3_tools"].format(
        tools=tools_str,
        knowledge_base=kb_str,
    ))

    # Section 4: Memory & Context
    sections.append(schema["4_memory"].format(
        memory_model=format_list(data.get("memory", [])),
        context_scope=data.get("context_scope", "*Not specified.*"),
    ))

    # Section 5: Constraints, Safety & Quality
    sections.append(schema["5_constraints"].format(
        boundaries=format_list(data.get("boundaries", [])),
        error_handling=format_list(data.get("error_handling", [])),
        quality=format_list(data.get("quality_standards", [])),
    ))

    # Section 6: Output & Interaction Format
    sections.append(schema["6_output"].format(
        output_types=format_list(data.get("output_types", [])),
        medium=data.get("medium", "*Not specified.*"),
        style_guide=format_list(data.get("style_guide", [])),
    ))

    # Section 7: Example Interaction
    sections.append(schema["7_example"].format(
        example_input=data.get("example_input", "*Example not provided.*"),
        example_output=data.get("example_output", "*Example not provided.*"),
    ))

    # Footer
    sections.append(schema["footer"])

    return "\n".join(sections)


def main():
    parser = argparse.ArgumentParser(
        description="Generate an agent definition document from JSON input."
    )
    parser.add_argument("input", type=str, help="Path to input JSON file")
    parser.add_argument("-o", "--output", type=str, default=None,
                        help="Output markdown file path (default: {name}-definition.md)")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    output = generate(data)

    name = data.get("name", "agent").lower().replace(" ", "-")
    output_path = Path(args.output) if args.output else Path(f"{name}-definition.md")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"Agent definition written to: {output_path.resolve()}")


if __name__ == "__main__":
    main()
